### ISSUE TITLE
Move old blog posts over to new format

### ISSUE THREAD

**Issue by Kriesse** [cssconf/blog-content#1]
From here: 
http://2014.cssconf.eu/news
http://2013.cssconf.eu/news

@verpixelt please assign this issue to me or @sfrdmn as soon as the structure is there and we’ll start to move over stuff. Also happy to show Polly and Lucie how to do this.

**Comment by verpixelt** [comment]
@Kriesse you can already move the content over there. We have a really really rough structure at the moment, but this shouldn't stop you.

**Comment by Kriesse** [comment]
Here's a tutorial on how to add/edit blog posts using the github web interface: https://github.com/cssconf/blog-content/wiki/How-To-Add-and-Edit-Blog-Posts

**Comment by Kriesse** [comment]
I moved this one: http://2014.cssconf.eu/news/thank-you-this-was-cssconf-eu-2014
It's now here: http://blog.cssconf.eu/2014/12/30/this-was-cssconf-eu-2014/
I am seeing errors, any idea why, @rendro @verpixelt @sfrdmn ?

**Comment by Kriesse** [comment]
Added another one:
http://blog.cssconf.eu/2014/12/17/announcing-cssconfeu-2015/
Now this one is showing the error, but the first one started to work. ¯_(ツ)_/¯

**Comment by sfrdmn** [comment]
<del>Can't reproduce. Maybe make sure you have the latest `blog-server` and do a `rm -Rf node_modules` and `npm install` on it. If you still get it, post the error output.</del>

**Comment by sfrdmn** [comment]
Oh never mind, here it is:

```
TypeError: Cannot read property 'toISOString' of undefined
   at [object Object].render (/Users/sean/Dropbox/Work/cssconf/blog-server/views/post.jsx:23:47)
   at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/Users/sean/Dropbox/Work/cssconf/blog-server/node_modules/react/lib/ReactCompositeComponent.js:789:34)
   at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (/Users/sean/Dropbox/Work/cssconf/blog-server/node_modules/react/lib/ReactCompositeComponent.js:816:14)
   at [object Object].wrapper [as _renderValidatedComponent] (/Users/sean/Dropbox/Work/cssconf/blog-server/node_modules/react/lib/ReactPerf.js:70:21)
   at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/sean/Dropbox/Work/cssconf/blog-server/node_modules/react/lib/ReactCompositeComponent.js:237:30)
   at [object Object].wrapper [as mountComponent] (/Users/sean/Dropbox/Work/cssconf/blog-server/node_modules/react/lib/ReactPerf.js:70:21)
   at /Users/sean/Dropbox/Work/cssconf/blog-server/node_modules/react/lib/ReactServerRendering.js:68:32
   at ReactServerRenderingTransaction.Mixin.perform (/Users/sean/Dropbox/Work/cssconf/blog-server/node_modules/react/lib/Transaction.js:134:20)
   at Object.renderToStaticMarkup (/Users/sean/Dropbox/Work/cssconf/blog-server/node_modules/react/lib/ReactServerRendering.js:66:24)
   at /Users/sean/Dropbox/Work/cssconf/blog-server/node_modules/consolidate/lib/consolidate.js:1162:74
   at /Users/sean/Dropbox/Work/cssconf/blog-server/node_modules/consolidate/lib/consolidate.js:146:5
   at tryCatcher (/Users/sean/Dropbox/Work/cssconf/blog-server/node_modules/consolidate/node_modules/bluebird/js/main/util.js:24:31)
   at Promise._resolveFromResolver (/Users/sean/Dropbox/Work/cssconf/blog-server/node_modules/consolidate/node_modules/bluebird/js/main/promise.js:427:31)
   at new Promise (/Users/sean/Dropbox/Work/cssconf/blog-server/node_modules/consolidate/node_modules/bluebird/js/main/promise.js:53:37)
   at promisify (/Users/sean/Dropbox/Work/cssconf/blog-server/node_modules/consolidate/lib/consolidate.js:139:10)
   at View.engine (/Users/sean/Dropbox/Work/cssconf/blog-server/node_modules/consolidate/lib/consolidate.js:1128:12)
```

Got this on `/2014/12/30/this-was-cssconf-eu-2014/`

Seems that this is the error you get when there is no corresponding blog content for the given URL. Somehow, the server is not finding that post, though I do see it in the `_imports` folder

**Comment by sfrdmn** [comment]
Ah OK, looks like we were probably just typing in the wrong URLs. I copied and pasted the URL @Kriesse was using, which is why I got the error. We probably want a friendly 404 page for these cases so no one gets confused.

**Comment by sfrdmn** [comment]
Aight, submitted a patch. Using a pull request since I just started looking at the code today
